import React from "react"
import { UserData } from "../types/user-data"
import Head from "next/head"
import Header from "./Header"

interface LayoutProps {
  user?: UserData
  children?: React.ReactNode
  title?: string
}

/**
 * JSX component representing a Layout component.
 * Responsible for general layout of the application.
 *
 */
function Layout({ user, title, children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>{title || "assignment-wt1-oauth"} </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header user={user} />
      {children}
    </>
  )
}

export default Layout
