import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { withIronSessionSsr } from 'iron-session/next'
import { OAuthURI, cookieOptions } from '../utils/config'
import { generateState } from '../utils/server-side-props'
import { IronSession } from 'iron-session'

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps ({ req }: any): Promise<any> {
      if (req.session?.tokens?.access_token) {
        return {
          redirect: {
            destination: '/profile',
            permanent: false,
          }
      }
    } else {
      req.session.state = generateState()
      await req.session.save()
      return {
        props: {
          state: req.session.state 
        }
      }
    }
  }, cookieOptions
)

function Home({ state }:IronSession) {
  return (
    <div className={styles.container}>
      <Head>
        <title>assignment-wt1-oauth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to this Oauth Application
        </h1>
        <div className={styles.grid}>
          <a href={state && OAuthURI(state)} className={styles.card}>
            <h2>Login &rarr;</h2>
            <p>Login with your GitLab credentials.</p>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
